services:

  hgtp_frontend_service:
    env_file:
      - ./hgtp_frontend/.env
    image: hgtp_frontend_img
    build:
      context: ./hgtp_frontend
      # target: development
    ports:
      - "3000:80"
    stdin_open: true
    volumes:
      - ./hgtp_frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - react-express
    depends_on:
      - hgtp_backend_service
  
  hgtp_reverse_proxy_service:
    image: hgtp_reverse_proxy_img
    build:
      context: ./hgtp_reverse_proxy
    ports:
      - "8080:8080"
    stdin_open: true
    restart: always
    networks:
      - react-express
    depends_on:
      - hgtp_frontend_service
      - hgtp_backend_service

  hgtp_backend_service:
    env_file:
      - hgtp_backend/.env
    image: hgtp_backend_img
    build:
      context: ./hgtp_backend
      # target: development
    stdin_open: true
    volumes:
      - ./hgtp_backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
    restart: always
    networks:
      - express-mongodb
      - react-express

  mongodb:
    env_file:
      - hgtp_backend/.env
    restart: always
    image: "mongodb/mongodb-community-server:6.0.8-ubi8"
    user: root
    volumes:
      - ./data_db:/data/db
    networks:
      - express-mongodb
    expose:
      - 27017

networks:
  react-express:
  express-mongodb:
