### Rerferences:
# 1. Compose build specs: https://docs.docker.com/compose/compose-file/build/
# Run the commands:
# a. Build: $ docker compose -f docker-compose-build.yaml build --parallel
# b. Push:  $ docker compose -f docker-compose-build.yaml push
services:
  reverseproxy:
    build:
      context: ./hgtp_reverse_proxy
    image: davidfullstack/hgtp_reverse_proxy_img:latest

  backend:
    build:
      context: ./hgtp_backend
    image: davidfullstack/hgtp_backend_img:latest

  frontend:
    build:
      context: ./hgtp_frontend
    image: davidfullstack/hgtp_frontend_img:latest