### References:
# 1. https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:  
  # Add your secret values here (base64 encoded)
  # Convert a string to base64 in Linux as below:
  # $ echo -n "admin" | base64
  # Database secret
  # Backend Environment Variables
  MONGODB_URL: mongodb://admin:admin@mongodb
  MONGODB_INITDB_ROOT_USERNAME: YWRtaW4=
  MONGODB_INITDB_ROOT_PASSWORD: YWRtaW4=